import { z } from 'zod';

export const FormSchema = z.object({
  nap: z.string().optional(),
  napDuration: z.string().optional(),
  tense: z.number().optional(),
  exercise: z.string().optional(),
  caffeine: z.string().optional(),
  caffeineQuantity: z.string().optional(),
  caffeineTime: z.string().optional(),
  alcohol: z.string().optional(),
  alcoholQuantity: z.string().optional(),
  alcoholTime: z.string().optional(),
  sleepMedications: z.string().optional(),
  sleepMedicationsQuantity: z.string().optional(),
  sleepMedicationsTime: z.string().optional(),
  bedtime: z.string().optional(),
  lightsOffTime: z.string().optional(),
  sleepLatency: z.string().optional(),
  wakeUpPlanned: z.string().optional(),
  wakeUpTime: z.string().optional(),
  finalNap: z.string().optional(),
  outBed: z.string().optional(),
  awakening: z.string().optional(),
  nightawake: z.string().optional(),
  timetoWake: z.string().optional(),
  disturbe: z.number().optional(),
  qualitySleep: z.number().optional(),
  rest: z.number().optional(),
  tired: z.number().optional(),
  drowsiness: z.number().optional(),
  note: z.string().optional(),
});

export const defaultValues = {
  nap: '',
  napDuration: null,
  tense: 0,
  exercise: '',
  caffeine: '',
  caffeineQuantity: '',
  caffeineTime: null,
  alcohol: '',
  alcoholQuantity: '',
  alcoholTime: null,
  sleepMedications: '',
  sleepMedicationsQuantity: '',
  sleepMedicationsTime: null,
  bedtime: null,
  lightsOffTime: null,
  sleepLatency: null,
  wakeUpPlanned: '',
  wakeUpTime: null,
  finalNap: null,
  outBed: null,
  awakening: '',
  nightawake: null,
  timetoWake: null,
  disturbe: 0,
  qualitySleep: 0,
  rest: 0,
  tired: 0,
  drowsiness: 0,
  note: '',
};

export type FormData = z.infer<typeof FormSchema>;
