export const QUESTIONS = [
  {
    instruction:
      'Legga le seguenti frasi e per ognuna segni la risposta che meglio descrive come si è sentito in questo periodo. Faccia riferimento agli ULTIMI 15 GIORNI, COMPRESO OGGI, e scelga la sua risposta:',
    questions: [
      { index: 1, text: 'Mi sono turbato per cose di poco conto' },
      { index: 2, text: 'Ho dormito bene e mi sono svegliato riposato' },
      { index: 3, text: 'Ho provato fastidio quando la gente parlava di me' },
      { index: 4, text: 'Mi sono goduto la vita' },
      {
        index: 5,
        text: "Ho sentito l'impulso a colpire o a far male a qualcuno",
      },
      { index: 6, text: 'Tutto mi è sembrato assurdo, irreale' },
      { index: 7, text: 'La vita merita di essere vissuta' },
      { index: 8, text: 'Mi è piaciuto fare qualcosa di pericoloso' },
      { index: 9, text: 'Mi è capitato di bere troppo e di ubriacarmi' },
      { index: 10, text: 'Sono stato sul punto di piangere' },
      { index: 11, text: 'Ho gustato il sapore dei cibi' },
      { index: 12, text: 'Sono stato preoccupato per possibili disgrazie' },
      { index: 13, text: 'Mi è pesato prendere qualsiasi decisione' },
      { index: 14, text: 'Stare solo mi ha fatto paura' },
      { index: 15, text: 'Ho avuto momenti di rabbia' },
      { index: 16, text: 'Vedevo possibilità di soluzione ai miei problemi' },
      { index: 17, text: 'Sono stato tormentato dai sensi di colpa' },
      { index: 18, text: 'Ho sentito un nodo alla gola' },
      { index: 19, text: 'Tutto mi è sembrato senza scopo' },
      {
        index: 20,
        text: 'Mi è venuto da prendere a calci o a schiaffi qualcuno',
      },
      { index: 21, text: 'Sono riuscito a parlare con gli altri' },
      { index: 22, text: 'Ho fatto cose che mi hanno interessato e coinvolto' },
      { index: 23, text: 'Mi sono preoccupato per cose di poca importanza' },
      { index: 24, text: 'Ho perso il controllo di me stesso' },
      { index: 25, text: 'Avrei voluto essere morto' },
      { index: 26, text: 'Mi è successo di lamentarmi' },
      {
        index: 27,
        text: 'Ho cercato di affrontare le difficoltà anziché evitarle',
      },
      { index: 28, text: 'Ho fatto cose che mi hanno dato soddisfazione' },
      {
        index: 29,
        text: 'Ho capito che qualcosa non funziona nella mia testa',
      },
      {
        index: 30,
        text: 'Qualcuno mi ha aiutato a risolvere i miei problemi personali',
      },
      { index: 31, text: 'Pensieri di scarsa importanza mi hanno infastidito' },
      {
        index: 32,
        text: 'Avrei voluto avere il coraggio di togliermi la vita',
      },
      { index: 33, text: 'Mi sono abbuffato di cibo' },
      { index: 34, text: 'Ho fatto sogni spaventosi' },
      { index: 35, text: 'Mi sono irritato' },
      {
        index: 36,
        text: 'Ho pensato cose molto brutte, da non poterne parlare',
      },
      { index: 37, text: 'Il futuro mi riserva qualcosa di buono' },
      { index: 38, text: 'Alla mattina mi sono sentito fiacco e senza forze' },
      { index: 39, text: 'Sono stato sul punto di fare del male a me stesso' },
      {
        index: 40,
        text: 'Sono soddisfatto degli obiettivi che ho raggiunto o che sto per raggiungere',
      },
    ],
  },
  {
    instruction: 'Negli ultimi 15 giorni, MI SONO SENTITO:',
    questions: [
      { index: 41, text: 'in forma' },
      { index: 42, text: 'allegro e spensierato' },
      { index: 43, text: 'aiutato dagli altri' },
      { index: 44, text: 'calmo' },
      { index: 45, text: 'turbato' },
      { index: 46, text: 'agitato' },
      { index: 47, text: 'abbandonato' },
      { index: 48, text: 'svalutato o preso in giro' },
      { index: 49, text: 'stanco senza motivo' },
      { index: 50, text: 'tranquillo' },
      { index: 51, text: 'sicuro di me' },
      { index: 52, text: 'giù' },
      { index: 53, text: 'capito dagli altri' },
      { index: 54, text: 'ansioso' },
      { index: 55, text: 'contento' },
      { index: 56, text: 'bene' },
      { index: 57, text: 'nervoso' },
      { index: 58, text: 'travolgere dalle difficoltà' },
      { index: 59, text: 'riposato' },
      {
        index: 60,
        text: 'in grado di reagire anche a difficoltà e fallimenti',
      },
      { index: 61, text: 'depresso' },
      { index: 62, text: 'respinto o rifiutato dagli altri' },
      { index: 63, text: 'rilassato' },
      { index: 64, text: 'teso' },
      { index: 65, text: 'di peso agli altri' },
      { index: 66, text: 'solo' },
    ],
  },
  {
    instruction: 'Negli ultimi 15 giorni, HO AVUTO:',
    questions: [
      { index: 67, text: 'preoccupazioni' },
      {
        index: 68,
        text: 'delle delusioni che non riesco a togliermi dalla testa',
      },
      { index: 69, text: 'difficoltà ad addormentarmi' },
      { index: 70, text: 'sbalzi di umore' },
      { index: 71, text: 'la sensazione che il peggio fosse ormai superato' },
      { index: 72, text: 'difficoltà a concentrarmi' },
      { index: 73, text: 'momenti di panico' },
      { index: 74, text: 'la sensazione di non poterne proprio più' },
      { index: 75, text: 'sensi di vuoto o confusione alla testa' },
      { index: 76, text: 'interesse per il sesso' },
      {
        index: 77,
        text: 'la percezione che qualcuno controllasse i miei pensieri',
      },
      { index: 78, text: 'appetito' },
      { index: 79, text: 'sensazioni di peso e stretta allo stomaco' },
      { index: 80, text: 'fiducia in me stesso' },
    ],
  },
];
