packages:
  - apps/*
  - packages/*
  - tools/*

catalog:
  '@hookform/resolvers': ^5.1.1
  '@tailwindcss/postcss': 4.1.11
  '@tanstack/react-query': ^5.80.2
  '@trpc/client': ^11.2.0
  '@trpc/react-query': ^11.2.0
  '@trpc/server': ^11.2.0
  '@trpc/tanstack-react-query': ^11.2.0
  '@types/node': ^22.0.0
  '@types/react': 19.1.8
  '@types/react-dom': ^19.0.0
  '@types/ws': ^8.18.0
  drizzle-kit: ^0.30.5
  drizzle-orm: 0.41.0
  drizzle-zod: 0.8.2
  eslint: ^9.23.0
  jose: ^6.0.12
  lucide-react: 0.525.0
  next: 15.4.2
  postcss: 8.5.6
  prettier: ^3.6.2
  prettier-plugin-tailwindcss: ^0.6.11
  react: 19.1.0
  react-dom: 19.1.0
  react-hook-form: 7.60.0
  superjson: ^2.2.1
  tailwind-merge: 3.3.1
  tailwindcss: 4.1.11
  tw-animate-css: 1.3.5
  typescript: ^5.8.3
  ws: ^8.18.1
  zod: ^3.23.8
