packages:
  - apps/*
  - packages/*
  - tools/*

catalog:
  '@hookform/resolvers': ^5.1.1
  '@tailwindcss/postcss': ^4.0.15
  '@tanstack/react-query': ^5.80.2
  '@trpc/client': ^11.2.0
  '@trpc/react-query': ^11.2.0
  '@trpc/server': ^11.2.0
  '@trpc/tanstack-react-query': ^11.2.0
  '@types/node': ^22.0.0
  '@types/react': ^19.0.0
  '@types/react-dom': ^19.0.0
  '@types/ws': ^8.18.0
  drizzle-kit: ^0.30.5
  drizzle-orm: ^0.41.0
  drizzle-zod: ^0.8.2
  eslint: ^9.23.0
  lucide-react: ^0.525.0
  next: ^15.0.0
  postcss: ^8.5.3
  prettier: ^3.6.2
  prettier-plugin-tailwindcss: ^0.6.11
  react: ^19.0.0
  react-dom: ^19.0.0
  react-hook-form: ^7.59.0
  superjson: ^2.2.1
  tailwind-merge: ^3.3.1
  tailwindcss: 4.1.11
  typescript: ^5.8.3
  ws: ^8.18.1
  zod: ^3.23.8
