export const available = [
  'cba-ve',
  'pq-16',
  'eriraos-cl',
  'gaf-sofas',
  'gad-7',
  'pswq-16',
  'ius-r',
  'dass-21',
  'pdss',
  'asrm',
  'mec-10',
  'aebs',
  'tefq-18',
  'phq-9',
  'bha',
  'hads',
  'ede-q',
  'pid-5',
  'pid-5-sf',
  'pid-5-bf',
  // 'wai-sr',
  // 'wai-srt',
  //'hcl-32',
  'eat-26',
  'asi-3',
  'haq',
  'ptsq',
  'sps',
  'gss',
  'mogs',
  'core-om',
] as const;

export const ADMINISTRATION_TYPES = [
  { name: 'CBA-VE', id: 'cba-ve' },
  { name: 'PQ-16', id: 'pq-16' },
  { name: 'ERIraos-CL', id: 'eriraos-cl' },
  { name: 'GAF/SOFAS', id: 'gaf-sofas' },
  { name: 'GAD-7', id: 'gad-7' },
  { name: 'PSWQ-16', id: 'pswq-16' },
  { name: 'IUS-R', id: 'ius-r' },
  { name: 'DASS-21', id: 'dass-21' },
  { name: 'PDSS', id: 'pdss' },
  { name: 'ASRM', id: 'asrm' },
  { name: 'HCL-32', id: 'hcl-32' },
  { name: 'BHA', id: 'bha' },
  { name: 'HADS', id: 'hads' },
  { name: 'MEC-10', id: 'mec-10' },
  { name: 'EAT-26', id: 'eat-26' },
  { name: 'AEBS', id: 'aebs' },
  { name: 'TEFQ-18', id: 'tefq-18' },
  { name: 'EDE-Q', id: 'ede-q' },
  { name: 'PHQ-9', id: 'phq-9' },
  { name: 'ASI-3', id: 'asi-3' },
  { name: 'HAQ', id: 'haq' },
  { name: 'PTSQ', id: 'ptsq' },
  { name: 'SPS', id: 'sps' },
  { name: 'GSS', id: 'gss' },
  { name: 'MOGS', id: 'mogs' },
  { name: 'PID-5', id: 'pid-5' },
  { name: 'PID-5-SF', id: 'pid-5-sf' },
  { name: 'PID-5-BF', id: 'pid-5-bf' },
  { name: 'CORE-OM', id: 'core-om' },
];
export const graphColors = {
  default: 'bg-emerald-400',
  warning: 'bg-yellow-400',
  danger: 'bg-red-400',
} as const;
