export const SYMPTOMS = [
  'Ritiro sociale',
  'Riservatezza/Timidezza',
  'Umore depresso',
  'Disturbo delle funzioni corporee',
  'Senso di rallentamento',
  'Comportamento/Interesse nel lavoto o studio',
  'Trascuratezza di sé',
  'Tensione/Nervosismo/Agitazione',
  'Irritabilità',
  'Affollamento delle idee/Fuga delle idee',
  'Sospettosità/Diffidenza',
  'Idee di riferimento/Autoriferimento',
  'Derealizzazione',
  'Cambiamento della percezione',
  'Interferenza nel pensiero',
  'Ideazione paranoide',
  'Allucinazioni',
] as const;
