export const QUESTIONS = [
  'Divento ansioso se devo scrivere di fronte ad altre persone',
  'Mi imbarazza usare i bagni pubblici',
  'Quando parlo con gli altri presto molta attenzione alla mia voce e alle reazioni altrui',
  'Mi innervosisco se le persone mi fissano mentre cammino per la strada',
  'Quando sono con altre persone ho il timore di arrossire',
  'Mi sento a disagio se devo entrare in una stanza dove gli altri sono già seduti',
  'Mi preoccupa il fatto di mostrarmi agitato o tremare quando qualcuno mi guarda',
  'Mi rende nervoso dovermi sedere di fronte a qualcuno sull’autobus o in treno',
  "Mi terrorizza l'idea che altre persone possano vedermi svenire o vomitare",
  'Trovo difficile bere qualcosa in mezzo a un gruppo di persone',
  'Mi imbarazza mangiare di fronte ad uno sconosciuto al ristorante',
  'Mi preoccupa che le persone trovino strano il mio comportamento',
  "Divento teso se devo trasportare un vassoio all'interno di un self-service affollato",
  'Ho paura di comportarmi in modo strano o inusuale di fronte ad altre persone',
  'Mi preoccupa poter fare qualcosa che attiri l’attenzione degli altri',
  'Quando sono in ascensore divento teso se le persone mi fissano',
  'Quando sto facendo una fila mi sento gli occhi degli altri addosso',
  'Divento nervoso quando parlo di fronte ad altre persone',
  'Mi preoccupa fare movimenti inconsueti di fronte ad altre persone',
  'Mi sento impacciato e teso se so che delle persone mi stanno guardando',
] as const;
