export const QUESTIONS = [
  {
    id: 1,
    text: 'Non mi preoccupo di essere colpevole o di poter meritare un rimprovero.',
    options: [
      'Mai vero',
      'Quasi mai vero',
      'Raramente vero',
      'Ogni tanto vero',
      'Spesso vero',
      'Quasi sempre vero',
      'Sempre vero',
    ],
  },
  {
    id: 2,
    text: 'Mi sembra che la maggior parte delle persone sopporti più serenamente di me la possibilità di essere giudicato colpevole.',
    options: [
      'Mai vero',
      'Quasi mai vero',
      'Raramente vero',
      'Ogni tanto vero',
      'Spesso vero',
      'Quasi sempre vero',
      'Sempre vero',
    ],
  },
  {
    id: 3,
    text: 'Cerco in tutti i modi di evitare di essere colpevole.',
    options: [
      'Mai vero',
      'Quasi mai vero',
      'Raramente vero',
      'Ogni tanto vero',
      'Spesso vero',
      'Quasi sempre vero',
      'Sempre vero',
    ],
  },
  {
    id: 4,
    text: 'Se non mi preoccupassi di poter essere giudicato colpevole, vivrei più serenamente.',
    options: [
      'Mai vero',
      'Quasi mai vero',
      'Raramente vero',
      'Ogni tanto vero',
      'Spesso vero',
      'Quasi sempre vero',
      'Sempre vero',
    ],
  },
  {
    id: 5,
    text: 'Il timore di essere colpevole di qualcosa di brutto, non influisce sulle cose che faccio e sul modo in cui vivo la mia vita.',
    options: [
      'Mai vero',
      'Quasi mai vero',
      'Raramente vero',
      'Ogni tanto vero',
      'Spesso vero',
      'Quasi sempre vero',
      'Sempre vero',
    ],
  },
  {
    id: 6,
    text: 'È doloroso meritare di essere giudicati colpevoli da qualcun altro.',
    options: [
      'Mai vero',
      'Quasi mai vero',
      'Raramente vero',
      'Ogni tanto vero',
      'Spesso vero',
      'Quasi sempre vero',
      'Sempre vero',
    ],
  },
  {
    id: 7,
    text: 'Se potessi magicamente eliminare tutte le esperienze in cui mi sono comportato male nella vita, vivrei più serenamente.',
    options: [
      'Mai vero',
      'Quasi mai vero',
      'Raramente vero',
      'Ogni tanto vero',
      'Spesso vero',
      'Quasi sempre vero',
      'Sempre vero',
    ],
  },
  {
    id: 8,
    text: 'Non ho paura di essere rimproverato.',
    options: [
      'Mai vero',
      'Quasi mai vero',
      'Raramente vero',
      'Ogni tanto vero',
      'Spesso vero',
      'Quasi sempre vero',
      'Sempre vero',
    ],
  },
  {
    id: 9,
    text: 'Mi sembra che la maggior parte delle persone tolleri il senso di colpa meglio di me.',
    options: [
      'Mai vero',
      'Quasi mai vero',
      'Raramente vero',
      'Ogni tanto vero',
      'Spesso vero',
      'Quasi sempre vero',
      'Sempre vero',
    ],
  },
];
