export const available = [
  'cba-ve',
  'pq-16',
  'eriraos-cl',
  'gaf-sofas',
  'gad-7',
  'pswq-16',
  'ius-r',
  'dass-21',
  'pdss',
  'asrm',
  'mec-10',
  'aebs',
  'tefq-18',
  'phq-9',
  'bha',
  'hads',
  'ede-q',
  'pid-5',
  'pid-5-sf',
  'pid-5-bf',
  // 'wai-sr',
  // 'wai-srt',
  //'hcl-32',
  'eat-26',
  'asi-3',
  'haq',
  'ptsq',
  'sps',
  'gss',
  'mogs',
  'core-om',
  'honosca',
] as const;

export const ADMINISTRATION_TYPES: {
  name: string;
  id: (typeof available)[number];
  disorder: string;
  info: string;
}[] = [
  {
    name: 'CBA-VE',
    id: 'cba-ve',
    disorder: 'Trasversale',
    info: 'Il CBA-VE Valutazione degli Esiti è uno strumento per la verifica dell’efficacia nella pratica dei trattamenti psicologici.',
  },
  {
    name: 'PQ-16',
    id: 'pq-16',
    disorder: 'UHR-FEP',
    info: 'Il PQ-16 è un breve strumento di screening progettato per identificare i sintomi prodromici della psicosi nei giovani adulti. ',
  },
  {
    name: 'ERIraos-CL',
    id: 'eriraos-cl',
    disorder: 'UHR-FEP',
    info: 'Qui vanno le informazioni relative al questionario utili al terapeuta',
  },
  {
    name: 'GAF/SOFAS',
    id: 'gaf-sofas',
    disorder: 'UHR-FEP',
    info: 'Qui vanno le informazioni relative al questionario utili al terapeuta',
  },
  {
    name: 'GAD-7',
    id: 'gad-7',
    disorder: 'Ansia',
    info: "Il GAD-7 è un questionario di stato, utile per misurare la presenza di sintomi d'ansia nelle due settimane precedenti. ",
  },
  {
    name: 'PSWQ-16',
    id: 'pswq-16',
    disorder: 'Ansia',
    info: "Il PSWQ è uno strumento self-report che indaga la frequenza e l’intensità del rimuginio, indipendentemente dai momenti e dalle situazioni. Si concentra principalmente sulla componente cognitiva dell'ansia, rilevando quindi il grado di preoccupazione in quanto pensiero persistente e ruminante.",
  },
  {
    name: 'IUS-R',
    id: 'ius-r',
    disorder: 'Ansia',
    info: "La IUS-R è un questionario self-report volto a valutare l’intolleranza all’incertezza (IU), ovvero la tendenza generale dell'individuo a considerare l'incertezza stressante e indesiderabile. ",
  },
  {
    name: 'DASS-21',
    id: 'dass-21',
    disorder: 'Ansia',
    info: 'La DASS-21 è un questionario autosomministrato di stato, originariamente costruito per discriminare i principali sintomi della depressione, dell’ansia e dello stress. ',
  },
  {
    name: 'PDSS',
    id: 'pdss',
    disorder: 'Ansia',
    info: 'Il PDSS è un questionario di autovalutazione volto a indagare la gravità e la frequenza dei sintomi del disturbo di panico durante l’ultimo mese. ',
  },
  {
    name: 'ASRM',
    id: 'asrm',
    disorder: 'Umore (mania-bipolare)',
    info: 'L’ASRM è uno strumento che valuta la presenza e/o la gravità dei sintomi maniacali negli ultimi sette giorni. ',
  },
  // {
  //   name: 'HCL-32',
  //   id: 'hcl-32',
  //   disorder: 'Umore (mania-bipolare)',
  //   info: "La HCL-32 è uno strumento di valutazione progettato per identificare i sintomi di ipomania e mania in individui che potrebbero soffrire di disturbi dell'umore, in particolare il disturbo bipolare.",
  // },
  {
    name: 'BHA',
    id: 'bha',
    disorder: 'Umore (depressione)',
    info: 'Il BHA valuta i sentimenti di assenza di speranza.',
  },
  {
    name: 'HADS',
    id: 'hads',
    disorder: 'Umore (depressione)',
    info: 'L’HADS è un questionario self-report che valuta ansia e depressione al netto della componente fisico-somatica, ideale per pazienti ospedalizzati o con problemi fisici. ',
  },
  {
    name: 'MEC-10',
    id: 'mec-10',
    disorder: 'Alimentare',
    info: "Il MEC-10 è un questionario di autovalutazione che valuta il comportamento alimentare compulsivo con modalità di abbuffata all'interno di un contesto più ampio di alimentazione disfunzionale.",
  },
  {
    name: 'EAT-26',
    id: 'eat-26',
    disorder: 'Alimentare',
    info: "L’EAT-26 è un questionario self-report di screening utilizzato per cogliere i tratti psicologici e i sintomi caratteristici dei disturbi dell'alimentazione dai 15 anni in su.",
  },
  {
    name: 'AEBS',
    id: 'aebs',
    disorder: 'Alimentare',
    info: 'L’AEBS è un questionario di autovalutazione che misura i comportamenti collegati alla dipendenza alimentare.',
  },
  {
    name: 'TEFQ-18',
    id: 'tefq-18',
    disorder: 'Alimentare',
    info: 'Il TFEQ-R-18 è un questionario utilizzato a livello internazionale per valutare tre dimensioni chiave del comportamento alimentare, ovvero restrizione cognitiva, alimentazione incontrollata e alimentazione emotiva. ',
  },
  {
    name: 'EDE-Q',
    id: 'ede-q',
    disorder: 'Alimentare',
    info: 'Qui vanno le informazioni relative al questionario utili al terapeuta',
  },
  {
    name: 'PHQ-9',
    id: 'phq-9',
    disorder: 'Umore (depressione)',
    info: 'Il PHQ-9 è uno strumento di screening che valuta la presenza e la gravità della depressione.',
  },
  {
    name: 'ASI-3',
    id: 'asi-3',
    disorder: 'Ansia',
    info: 'L’ASI-3 è un questionario self-report che misura il grado di preoccupazione per le possibili conseguenze negative dei sintomi di ansia. ',
  },
  {
    name: 'HAQ',
    id: 'haq',
    disorder: 'Ansia',
    info: 'L’HAQ è un questionario di autovalutazione volto a misurare l’ansia relativa alla salute. ',
  },
  {
    name: 'PTSQ',
    id: 'ptsq',
    disorder: 'Ansia',
    info: 'Il PTSQ è uno strumento self-report utile per identificare e valutare i sintomi del disturbo da stress post-traumatico (PTSD).',
  },
  {
    name: 'SPS',
    id: 'sps',
    disorder: 'Ansia',
    info: 'La SPS è un questionario self-report che indaga i sintomi del disturbo d’ansia sociale, ovvero le situazioni in cui il soggetto, mentre compie gesti e azioni, viene osservato e questo provoca in lui ansia',
  },
  {
    name: 'GSS',
    id: 'gss',
    disorder: 'Ossessivo',
    info: 'La GSS è una scala composta da 10 item sviluppata per misurare la sensibilità alla colpa, intesa come la tendenza soggettiva a valutare negativamente il sentimento di colpa e i suoi effetti. ',
  },
  {
    name: 'MOGS',
    id: 'mogs',
    disorder: 'Ossessivo',
    info: 'La MOGS è uno strumento sviluppato per misurare in modo distinto le diverse forme che può assumere il senso di colpa, in relazione all’orientamento morale dell’individuo. ',
  },
  {
    name: 'PID-5',
    id: 'pid-5',
    disorder: 'Personalità',
    info: 'Il PID-5- 220-item è un questionario che valuta i tratti di personalità patologici secondo i criteri del modello alternarivo del DSM-5 per i disturbi di personalità. ',
  },
  {
    name: 'PID-5-SF',
    id: 'pid-5-sf',
    disorder: 'Personalità',
    info: 'Qui vanno le informazioni relative al questionario utili al terapeuta',
  },
  {
    name: 'PID-5-BF',
    id: 'pid-5-bf',
    disorder: 'Personalità',
    info: 'Il PID-5-Brief Form è un questionario che valuta i tratti di personalità patologici secondo i criteri del modello alternarivo del DSM-5 per i disturbi di personalità. ',
  },
  {
    name: 'CORE-OM',
    id: 'core-om',
    disorder: 'Trasversale',
    info: 'Il CORE-OM è uno sturmento progettato per misurareI gli esiti in psicoterapia e valuta il livello di disagio psicologico e dei problemi che il paziente ha sperimentato nel corso dell’ultima settimana. ',
  },
  {
    name: 'HONOSCA',
    id: 'honosca',
    disorder: 'UHR-FEP',
    info: 'Qui vanno le informazioni relative al questionario utili al terapeuta',
  },
];

export const graphColors = {
  default: 'bg-emerald-400',
  warning: 'bg-yellow-400',
  danger: 'bg-red-400',
} as const;
